#pragma config(Sensor, S1,     T1,             sensorTouch)
#pragma config(Sensor, S2,     IR1,            sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          PICKUP,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RIGHT,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          LEFT,          tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define MAXRESETTIME 3000
void pickup ()
{
	motor[motorB] = 0;
	motor[motorC] = 0;
	nMotorEncoder[motorA] = 0;
	while( nMotorEncoder[motorA] > -720  )
	{
		motor[motorA] = -75;
	}
	motor[motorA] = 0;
	ClearTimer(T1);
	while(!SensorValue(S1) && time1[T1] < MAXRESETTIME)
	{
		motor[motorA] = -50;
	}
	motor[motorA] = 0;
}

task main()
{
	int pause=0;

	int slow = 1;
	int power;
	int seekerVal = -1;

	bFloatDuringInactiveMotorPWM = false;  // brake
	while(1)
	{

		//if( SensorValue(S2) != seekerVal && SensorValue(S2)!= 0)
		//{
		//	seekerVal = SensorValue(S2);
		//	writeDebugStreamLine("Seeker Val: %d ", seekerVal);
		//}

		getJoystickSettings(joystick);
		//Check to enable / disable robot controls
		if( joy2Btn(2) == 1 )
		{
			pause = 0;
		}
		if( joy2Btn(3) == 1 || pause )
		{
			motor[motorB] = 0;
			motor[motorC] = 0;
			motor[motorA] = 0;
			pause = 1;
			continue;
		}

		if(joy1Btn(1))
			slow = 0;
		else if(joy1Btn(3))
			slow = 1;

		if( slow )
			power = 10;
		else
			power = 26;

		if(joy1Btn(5))
			power *= 2;

		if(joystick.joy1_x2 > 13 || joystick.joy1_x2 < -13)     // turn
		{

			if(joystick.joy1_x2 > 0)
				power = -1 * power;

			motor[motorB] = power;
			motor[motorC] = -1 * power;
		}
		else if( joystick.joy1_y1 > 13 || joystick.joy1_y1 < -13)  /* straight */
		{
			if(joystick.joy1_y1 < 0)
				power = -1 * power;

			motor[motorB] = power;
			motor[motorC] = power;
		}
		//else
		else if(joy1Btn(2))
			motor[motorA] = -75;
			//pickup();
		else
		{
			motor[motorA] = 0;
			motor[motorB] = 0;
			motor[motorC] = 0;
		}
	}

}
