#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     car,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	ClearTimer(T1);
	int target = 1;
	while(time100[T1] < 300)
	{
		if(nNxtButtonPressed == 3)
		{
			ClearTimer(T1);
			target *= -1;
			PlayTone(440, 10);
			wait1Msec(100);
		}

		else if(nNxtButtonPressed == 1)
		{
			ClearTimer(T1);
			if(target == 1)
				motor[elevator] = 40;
			else if(target == -1)
				motor[car] = 50;
		}
		else if(nNxtButtonPressed == 2)
		{
			ClearTimer(T1);
			if(target == 1)
				motor[elevator] = -40;
			else if(target == -1)
				motor[car] = -50;
		}
		else
		{
			motor[elevator] = 0;
			motor[car] = 0;
		}
	}



}
