#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     thing1,         sensorLightActive)
#pragma config(Sensor, S3,     thing2,         sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     fan,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "TheGreatLibrary.c"
#include "ButtonDriver.h"


task main()
{

	clearDebugStream();
	ClearTimer(T1);
	ClearTimer(T4);

	while(1)
	{
		getEvents();

		for(int i = 0; i<eventCnt;i++)
		{
			switch(bevents[i].keyID){
			case JOY1_GREEN:
			if(bevents[i].state == B_PRSD)
				motor[fan] = 90;
		else if(bevents[i].state == B_RLSD)
				motor[fan] = 0;
			break;
			case JOY1_BLUE:
			if(bevents[i].state == B_PRSD)
				motor[fan] = 30;
		else if(bevents[i].state == B_RLSD)
				motor[fan] = 0;
			break;
			};
		}



		//_________________________________________________________________________



	}
}
