#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Rollers,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(1)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(1))
			motor[Rollers] = 50;
		else if(joy1Btn(3))
			motor[Rollers] = -50;
	else
		motor[Rollers] = 0;

		if(joy1Btn(2))
			motor[Arm] = -50;
		else if(joy1Btn(4))
			motor[Arm] = 50;
	else
		motor[Arm] = 0;

	}



}
