#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     lowerTouch,     sensorTouch)
#pragma config(Sensor, S3,     upperLight,     sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FlagRaiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     LeftBack,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     RightBack,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    release,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hatch,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define LIGHT_THRESH 50

//void deploySpinyDU(int GoButton, int StopButton);
void TakeADump(int GoButton, int StopButton);
void WaywardSon(bool upButton, bool downButton, int stopbutton);

int SpinyDuDeployed = 0;

short auxButton(int button){
	return joy1Btn(button);
}

task main()
{
	clearDebugStream();
	ClearTimer(T1);
	ClearTimer(T2);
	ClearTimer(T3);
	servo[release] = 0;
	servo[hatch] = 95;
	//wait10Msec(50);
	//servo[hatch] = 0;


	while(1)
	{
		getJoystickSettings(joystick);
		//deploySpinyDU(auxButton(7), auxButton(3));
		TakeADump(auxButton(8), auxButton(3));
		WaywardSon(joystick.joy1_TopHat == 0, joystick.joy1_TopHat == 4, auxButton(3));

		//if(SpinyDuDeployed)
		//{
		//	if(auxButton(4))
		//		motor[FlagRaiser] = 100;
		//	else if(auxButton(2))
		//		motor[FlagRaiser] = -5;
		//	else
		//		motor[FlagRaiser] = 0;
		//}
		//else
			motor[FlagRaiser] = 0;

		//static bool wasMoving = false;
		//if(abs(joystick.joy2_y2) > 10)
		//{
		//	motor[Arm] = -(joystick.joy2_y2*100)/128;
		//	wasMoving = true;
		//	}else if (wasMoving){
		//	motor[Arm] = 0;
		//	wasMoving = false;
		//}


		int leftpower = 0;
		int rightpower = 0;
		int slow = 0;
		int xslow = 0;

		int yaxis = -joystick.joy1_y2;
		int xaxis = joystick.joy1_x1;

		leftpower = yaxis + xaxis;
		rightpower = yaxis - xaxis;

		//change "gears"
		if(joy1Btn(5))
			xslow = 1;
		else if(joy1Btn(6))
			slow = 1;
		else
		{
			slow = 0;
			xslow = 0;
		}

		if(xslow)
		{
			if(time1[T1] >= 250)
				writeDebugStreamLine("xslow");
			leftpower /= 5;
			rightpower /= 5;
		}

		else if(slow)
		{
			if(time1[T1] >= 250)
				writeDebugStreamLine("slow");
			leftpower /= 2;
			rightpower /= 2;
		}

		//scale from joystick outputs to motors
		leftpower = (leftpower*100)/128;
		rightpower = (rightpower*100)/128;

		//if a side would get insignificant power just turn it off
		if(abs(leftpower) < 10)
			leftpower = 0;
		if(abs(rightpower) < 10)
			rightpower = 0;

		if(time1[T1] >= 250)
		{
			ClearTimer(T1);
			writeDebugStreamLine("leftpower: %d" , leftpower);
			writeDebugStreamLine("rightpower: %d" , rightpower);
		}


		motor[LeftFront] = leftpower;
		motor[LeftBack] = leftpower;
		motor[RightFront] = rightpower;
		motor[RightBack] = rightpower;
	}

}

void deploySpinyDU(int GoButton, int StopButton)
{
	static int timelimit = 0;
	static int Stop = 0;

	if(StopButton)
	{
		SpinyDuDeployed = 0;
		servo[release] = 0;
		Stop = 1;
		return;
	}

	else if(GoButton)
	{
		Stop = 0;
		timelimit = time1[T2] + 500;
		servo[release] = 75;
		SpinyDuDeployed = 1;
		return;
	}


	else if(time1[T2] >= timelimit || Stop)
	{
		servo[release] = 0;
		Stop = 1;
		return;
	}
}

void TakeADump(int GoButton, int StopButton)
{
	static int Stop = 0;
	static int stageLimit = 1500;
	static int stage = 2;
	const int openPosition = 0;

	if(StopButton){
		Stop = 1;
	}

	else if(GoButton)
	{
		writeDebugStreamLine("Go");
		stage = 0;
		Stop = 0;
	}

	if(Stop)
	{
		servo[hatch] = openPosition;
		stage = 2;
		return;
	}

	if(stage == 0)
	{
		servo[hatch] = openPosition;
		ClearTimer(T4);
		stage = 1;
		return;
	}

	else if(stage == 1)
	{
		if(time1[T4] >= stageLimit)
		{
			servo[hatch] = 95;
			stage = 2;
		}
		return;
	}
}

bool armIsUp();
bool armIsDown();

void WaywardSon(bool upButton, bool downButton, int stopbutton)
{
	static int Target = -1;
	const long timelimit = 5001;
	static bool goingUp = false;
	static bool goingDown = false;
	static long startTime = 0;


	if(upButton) //up
	{
		startTime = nPgmTime;
		goingUp = true;
		goingDown = false;
	}
	else if(downButton) //down
	{
		startTime = nPgmTime;
		goingUp = false;
		goingDown = true;
	}

	if(stopbutton || nPgmTime > timelimit + startTime)
	{
		motor[Arm] = 0;
		goingDown = goingUp = false;
		return;
	}

	if (goingUp) {
		if(armIsUp()){
			motor[Arm] = 0;
			goingUp = false;
		}
		else{
			motor[Arm] = -20;
		}
	}
	if (goingDown) {
		if(armIsDown()){
			motor[Arm] = 0;
			goingDown = false;
		}
		else{
			motor[Arm] = 20;
		}
	}



}

bool armIsUp(){
	return SensorValue[upperLight] < LIGHT_THRESH;
}

bool armIsDown(){
	return SensorValue[lowerTouch];
}
