#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     thing1,         sensorLightActive)
#pragma config(Sensor, S3,     thing2,         sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ButtonDriver.h"
#include "JoystickDriver.c"

task main()
{

	clearDebugStream();
	ClearTimer(T1);
	ClearTimer(T4);

	while(1)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(2))
			motor[elevator] = -50;
		else if(joy1Btn(4))
			motor[elevator] = 50;
		else
			motor[elevator] = 0;

		//getEvents();

		//for(int i = 0; i<eventCnt;i++)
		//{
		//	switch(bevents[i].keyID){
		//	case JOY1_YELLOW :
		//		if(bevents[i].state == B_PRSD)
		//			motor[elevator] = 10;
		//		else if(bevents[i].state == B_RLSD)
		//			motor[elevator] = 0;
		//		break;
		//		case JOY1_GREEN:
		//		if(bevents[i].state == B_PRSD)
		//			motor[elevator] = -10;
		//		else if(bevents[i].state == B_RLSD)
		//			motor[elevator] = 0;
		//	break;
		//	};
		//}



		//_________________________________________________________________________



	}
}
