#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left_front,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Left_back,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right_front,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Right_back,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THREASH 13

task main()
{

	while(1)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y2) > JOY_THREASH)
		{
			motor[Left_back] = ((joystick.joy1_y2 * 100)/128)/3;
			motor[Left_front] = ((joystick.joy1_y2 * 100)/128)/3;
		}
		else
			motor[Left_back] = motor[Left_front] = 0;

		if(abs(joystick.joy1_y1) > JOY_THREASH)
		{
			motor[Right_back] = ((joystick.joy1_y1 * 100)/128)/3;
			motor[Right_front] = ((joystick.joy1_y1 * 100)/128)/3;
		}
		else
			motor[Right_back] = motor[Right_front] = 0;

	}


}
