#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     seeker,         sensorI2CCustom)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     arms,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FL,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     FR,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "TheGreatLibrary.c"

#define JOY_THRESH 12

int mode = 0;

////////////////////////////////////////////////////////////////////////////// TASK MAIN!!! \(^0^)/

task main()
{

	clearDebugStream();
	int power = 0;
	ClearTimer(T1);
	ClearTimer(T4);
	int forward = 1;
	nMotorEncoder[kicker1] = 0;
	nMotorEncoder[kicker2] = 0;

	//waitForStart();
	//waywardSon(-1, 1);

	while(1)
	{
		getJoystickSettings(joystick);

		//writeDebugStreamLine("%d", joystick.joy1_TopHat);




		//_________________________________
		float leftpower = 0;
		float rightpower = 0;
		int slow = 0;
		int xslow = 0;

		if(joy1Btn(2))
			forward = 0;
		else if(joy1Btn(4))
			forward = 1;

		int yaxis = joystick.joy1_y2;
		int xaxis = joystick.joy1_x1;

		leftpower = yaxis - xaxis;
		rightpower = yaxis + xaxis;

		//change "gears"
		if(joy1Btn(5))
			xslow = 1;
		else if(joy1Btn(6))
			slow = 1;
		else
		{
			slow = 0;
			xslow = 0;
		}

		if(xslow)
		{
			leftpower /= 3;
			rightpower /= 3;
		}

		else if(slow)
		{
			leftpower /= 2;
			rightpower /= 2;
		}

		//scale from joystick outputs to motors
		leftpower = (leftpower*100)/128;
		rightpower = (rightpower*100)/128;

		//if a side would get insignificant power just turn it off
		if(abs(leftpower) < 10)
			leftpower = 0;
		if(abs(rightpower) < 10)
			rightpower = 0;
		if(forward)
		{
			motor[FL] = leftpower;
			motor[BL] = leftpower;
			motor[FR] = rightpower;
			motor[BR] = rightpower;
		}
		else
		{
			motor[FR] = leftpower;
			motor[BR] = leftpower;
			motor[FL] = rightpower;
			motor[BL] = rightpower;
		}


	}


}
