#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     seeker,         sensorI2CCustom)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "TheGreatLibrary.c"

#define JOY_THRESH 12

int mode = 0;

////////////////////////////////////////////////////////////////////////////// TASK MAIN!!! \(^0^)/

task main()
{

	clearDebugStream();
	int power = 0;
	ClearTimer(T1);
	ClearTimer(T4);
	int forward = 1;
	nMotorEncoder[kicker1] = 0;
	nMotorEncoder[kicker2] = 0;
	writeDebugStreamLine("arm encoder %d" , nMotorEncoder[arms]);

	//waitForStart();
	//waywardSon(-1, 1);

	while(1)
	{
		getJoystickSettings(joystick);

		//writeDebugStreamLine("%d", joystick.joy1_TopHat);


		if(time1[T1] >= 750)
		{
			//writeDebugStreamLine("arm encoder %d" , nMotorEncoder[arms]);
			writeDebugStreamLine("wrist encoder %d" , nMotorEncoder[wrist]);
			//writeDebugStreamLine("kicker encoder %d" , nMotorEncoder[kicker1]);
			ClearTimer(T1);
		}



		if(!mode)
		{
			if(joy1Btn(10))
				mode = 1;

			if(joy1Btn(7))
				motor[tailWinch] = - 50;
			else if(joy1Btn(8))
				motor[tailWinch] = 90;
			else
				motor[tailWinch] = 0;
			//_________________________________
			if(joy1Btn(3))
			{
				motor[kicker1] = 100;
				motor[kicker2] = 100;
			}
			else if(joy1Btn(1))
			{
				motor[kicker1] = -100;
				motor[kicker2] = -100;
			}
			else
			{
				motor[kicker1] = 0;
				motor[kicker2] = 0;
			}
			//_________________________________
			float leftpower = 0;
			float rightpower = 0;
			int slow = 0;
			int xslow = 0;

			if(joy1Btn(2))
				forward = 0;
			else if(joy1Btn(4))
				forward = 1;

			int yaxis = joystick.joy1_y2;
			int xaxis = joystick.joy1_x2;

			leftpower = yaxis + xaxis;
			rightpower = yaxis - xaxis;

			//change "gears"
			if(joy1Btn(5))
				xslow = 1;
			else if(joy1Btn(6))
				slow = 1;
			else
			{
				slow = 0;
				xslow = 0;
			}

			if(xslow)
			{
				leftpower /= 3;
				rightpower /= 3;
			}

			else if(slow)
			{
				leftpower /= 2;
				rightpower /= 2;
			}

			//scale from joystick outputs to motors
			leftpower = (leftpower*100)/128;
			rightpower = (rightpower*100)/128;

			//if a side would get insignificant power just turn it off
			if(abs(leftpower) < 10)
				leftpower = 0;
			if(abs(rightpower) < 10)
				rightpower = 0;
			if(forward)
			{
				motor[FL] = leftpower;
				motor[BL] = leftpower;
				motor[FR] = rightpower;
				motor[BR] = rightpower;
			}
			else
			{
				motor[FR] = leftpower;
				motor[BR] = leftpower;
				motor[FL] = rightpower;
				motor[BL] = rightpower;
			}
			if(takeAdump(joy1Btn(2), joy1Btn(1)))
			{	if(abs(joystick.joy1_y1) > JOY_THRESH)
				{
					power = 30;
					if(joystick.joy1_y1 < 0)
					{
						power *= -1;
					}
					if(joy1Btn(5))
						power /= 3;

					motor[wrist] = power;
				}
				else
					motor[wrist] = 0;
			}


			if(waywardSon(joystick.joy1_TopHat, joy1Btn(1)))
			{

			}

		}
		else if(mode)
		{
			if(joy1Btn(9))
				mode = 0;

			if(joy1Btn(10))
			{
				nMotorEncoder[arms] = 0;
				nMotorEncoder[wrist] = 0;
			}
			//_________________________________
			if(joy1Btn(3))
			{
			}
			//	takeAbite();
			//_________________________________

			//_________________________________
			if(joy1Btn(7))
				motor[hookWinch] = 100;

			else if(joy1Btn(8))
				motor[hookWinch] = -100;

			else
				motor[hookWinch] = 0;
			//_________________________________

		}

	}
	//if(joy1Btn(9))
	//	joy1override = 1;
	//else if(joy1Btn(10))
	//	joy1override = 0;

	//kickTheBucket(joy1Btn(3), joy1Btn(1));
	//takeAdump(joy2Btn(2), joy2Btn(1));
	//waywardSon(joystick.joy2, joy2Btn(1));











	//if(joy1override)
	//{

	//}



	/////////////////////////////////////////////////


}
