#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     seeker,         sensorI2CCustom)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"

int checkCancel(int stop1, int stop2)
{
	getJoystickSettings(joystick);

	if(stop1 || stop2)
		return 1;
	else
		return 0;
}

void takeAbite()
{

	ClearTimer(T3);
	// lower arms
	while(nMotorEncoder[arms] <= -400 && time1[T3] <= 2000)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[arms] = 30;
	}

	motor[arms] = 0;
	ClearTimer(T3);

	// lower wrist
	while(nMotorEncoder[wrist] >= -1000 && time1[T3] <= 1000)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = -30;
	}
	motor[wrist] = 0;
	ClearTimer(T3);

	// make sure wrist is flush
	while(time1[T3] <= 250)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = -5;
	}
	motor[wrist] = 0;
	ClearTimer(T3);
	ClearTimer(T4);


	// move forward
	while(time1[T3] <= 1800)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = 30;
		motor[BR] = 30;
		motor[FL] = 30;
		motor[BL] = 30;
	}
	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;

	ClearTimer(T3);

	while(time1[T3] <= 100)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = -15;
		motor[BR] = -15;
		motor[FL] = -15;
		motor[BL] = -15;
	}

	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	ClearTimer(T3);

	// raise wrist
	while(nMotorEncoder[wrist] <= -600 && time1[T3] <= 750)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = 40;
	}
	motor[wrist] = 0;
	ClearTimer(T3);


	// drive back
	while(time1[T3] <= 900)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = -40;
		motor[BR] = -40;
		motor[FL] = -40;
		motor[BL] = -40;
	}

	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	return;
}

int takeAdump(int button, int stopbutton)
{
	static int Stop = 0;
	static int timelimit = 0;
	static int stage = 0;

	if(stopbutton)
		Stop = 1;
	else if(button)
	{
		Stop = 0;
		stage = 0;
		timelimit = 1500;
		ClearTimer(T4);
	}

	if(Stop)
	{
		motor[wrist] = 0;
		return 1;
	}

	if(time1[T4] >= timelimit)
	{
		motor[wrist] = 0;
		return 1;
	}

	if(stage == 0)
	{
		motor[wrist] = -40;
		if(nMotorEncoder[wrist] <= -1600)
		{
			motor[wrist] = 0;
			stage = 1;
		}
	}
	else if(stage == 1)
	{
		motor[wrist] = 40;
		if(nMotorEncoder[wrist] >= -800)
		{
			motor[wrist] = 0;
			Stop = 1;
			stage = 0;
			return 1;
		}
	}
	return 0;
}

int waywardSon(int hatValue, int stopbutton)
{
	static int Stop = 1;
	static int targetHeight = 0;
	const int timelimit = 3000;

	if(stopbutton)
		Stop = 1;
	else if(hatValue%2 == 0)
	{
		Stop = 0;
		ClearTimer(T2);

		switch (hatValue)
		{
		case 4: //move arm to bottom pos
			targetHeight = -25;
			break;
		case 2: //High medium
			targetHeight = -5000;
			break;
		case 6: //Low medium
			targetHeight = -4000;
			break;
		case 0: //hang
			targetHeight = -6700;
			break;
		default: //something is terribly wrong
			Stop=1;
		}

	}

	if(Stop)
	{
		return 1;
	}

	if(time1[T2] >= timelimit)
	{
		Stop = 1;
		return 1;
	}

	if(nMotorEncoder[arms] >= targetHeight + 50)
	{
		motor[arms] = -40;
	}
	else if(nMotorEncoder[arms] <= targetHeight - 50)
	{
		motor[arms] = 40;
	}
	else
	{
		motor[arms] = 0;
		Stop = 1;
	}
	return 0;
}



void MissionImpossible()
{
  //        100 = Tempo
  //          6 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  988,    7); wait1Msec(  75);  // Note(E, Duration(32th))
  PlayTone( 1047,    7); wait1Msec(  75);  // Note(F, Duration(32th))
  PlayTone( 1109,    7); wait1Msec(  75);  // Note(F#, Duration(32th))
  PlayTone( 1175,    7); wait1Msec(  75);  // Note(G, Duration(32th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  880,  108); wait1Msec(1200);  // Note(D, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  831,  108); wait1Msec(1200);  // Note(C#, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  784,  108); wait1Msec(1200);  // Note(C, Duration(Half))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  932,   14); wait1Msec( 150);  // Note(A#5, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  return;
}
