#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     seeker,         sensorI2CCustom)
#pragma config(Motor,  motorA,          stuffer,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          deploySweep,   tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          sweeper,       tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     FrontL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BackR,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightRoller,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftRoller,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     car,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S3_C1_1,    grabberServo,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_2,    dropperServo,         tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    sweeperServo,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// !! Changes to motor configuration must be copied to all files !! //

#define DEBUG true
#define DO_EXTEND false

#include "JoystickDriver.c"

#include "AutoLib.h"


void onRamp()
{
	wait1Msec(1500);
	move(-180, 35);
	//wait1Msec(1000);
	if (DO_EXTEND) liftFirstStage();
	wait1Msec(1000);
	move(-60, 35);
	wait1Msec(1000);
	grabGoal();
	wait1Msec(1000);
	dumpBalls(true);
	wait1Msec(1000);
	turnFromLWall(-170, 80);
	wait1Msec(1000);
	move(-240, 40);
}

task main()
{
	gyroCal();
	waitForStart();
	clearDebugStream();
	writeDebugStreamLine("starting!");
	nMotorEncoder[FrontL] = 0;
	nMotorEncoder[FrontR] = 0;
	nMotorEncoder[car] = 0;
	nMotorEncoder[elevator] = 0;
	nMotorEncoder[sweeper] = 0;
	nMotorEncoder[deploySweep] = 0;

	onRamp();
}
