#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          lateralSweep,  tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          stuffer,       tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          verticalSweep, tmotorNXT, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     FrontL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     BackL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FrontR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     BackR,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightRoller,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftRoller,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     elevator,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     car,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S3_C1_1,    grabberServo,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_2,    dropperServo,         tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    sweeperServo,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool testMotor(int mot, int enc, const string name);

task main()
{
	testMotor(lateralSweep, lateralSweep, "lateralSweep");
	testMotor(stuffer, stuffer, "Stuffer");
	testMotor(verticalSweep, verticalSweep, "Vertical Sweeps");
	testMotor(FrontL, FrontL, "Front Left");
	testMotor(BackL, FrontL, "Back Left");
	testMotor(FrontR, FrontR, "Front Right");
	testMotor(BackR, FrontR, "Back Right");
	//testMotor(rightRoller, rightRoller, "Right Roller"); //These motors don't have encoders.
	//testMotor(leftRoller, leftRoller, "Left Roller"); //These motors don't have encoders.
	testMotor(elevator, elevator, "Elevator");
	testMotor(car, car, "Car");
}

bool testMotor(int mot, int enc, const string name){
	eraseDisplay();
	nxtDisplayCenteredTextLine(2, "Testing Motor:");
	nxtDisplayCenteredTextLine(3, name);
	time1[T1] = 0;
	nMotorEncoder[enc] = 0;

	bool passed = true;
	int power = 5;
	while (abs(nMotorEncoder[enc]) < 2){
		writeDebugStreamLine("Encoder value: %d", nMotorEncoder[enc]);
		motor[mot] = power;
		power++;
		wait1Msec(5);
		if (time1[T1] > 500){
			passed = false;
			break;
		}
	}
	motor[mot] = 0;

	nxtDisplayCenteredTextLine(2, "Test %s:", passed ? "passed":"failed");
	while(nNxtButtonPressed != -1){wait1Msec(5);}
	while(nNxtButtonPressed != 3){wait1Msec(5);}
	while(nNxtButtonPressed != -1){wait1Msec(5);}
	return true;

}
