#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[arm] = 0;
	while(nMotorEncoder[arm] > - 360)
		motor[arm] = -100;

	while(nMotorEncoder[arm] < 0)
		motor[arm] = 30;
	motor[arm] =0;
}
