#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
typedef enum
{
	DRIVER,
	WAYWARD_SON,
	TAKE_A_BITE
} WhoHasControl;

WhoHasControl armMode = DRIVER;

#include "JoystickDriver.c"

#define JOY_THRESH 12

int checkCancel(int stop1, int stop2)
{
	getJoystickSettings(joystick);

	if(stop1 || stop2)
		return 1;
	else
		return 0;
}

void kickTheBucket(int button, int stopbutton)
{
	static int Stop = 0;
	static int timelimit = 0;
	static int stage = 0;

	if(stopbutton)
		Stop = 1;
	else if(button)
	{
		Stop = 0;
		stage = 0;
		timelimit = time1[T4] + 1500;
	}

	if(Stop)
	{
		motor[kicker1] = 0;
		motor[kicker2] = 0;
		return;
	}

	if(time1[T4] >= timelimit)
	{
		motor[kicker1] = 0;
		motor[kicker2] = 0;
		return;
	}
	if(stage == 0)
	{
		motor[kicker1] = 100;
		motor[kicker2] = 100;
		if(nMotorEncoder[kicker1] >= 550)
		{
			motor[kicker1] = 0;
			motor[kicker2] = 0;
			stage = 1;
		}
	}
	else if(stage == 1)
	{
		motor[kicker1] = -50;
		motor[kicker2] = -50;
		if(nMotorEncoder[kicker1] <= 25)
		{
			motor[kicker1] = 0;
			motor[kicker2] = 0;
			stage = 2;
		}
	}
}

void takeAbite()
{

	ClearTimer(T3);
	// lower arms
	while(nMotorEncoder[arms] <= -400 && time1[T3] <= 2000)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[arms] = 30;
	}
	motor[arms] = 0;
	ClearTimer(T3);

	// lower wrist
	while(nMotorEncoder[wrist] >= -1000 && time1[T3] <= 1000)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = -30;
	}
	motor[wrist] = 0;
	ClearTimer(T3);

	// make sure wrist is flush
	while(time1[T3] <= 500)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = -10;
	}
	motor[wrist] = 0;
	ClearTimer(T3);
	ClearTimer(T4);


	// move forward
	while(time1[T3] <= 1800)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = 30;
		motor[BR] = 30;
		motor[FL] = 30;
		motor[BL] = 30;
	}
	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;

	ClearTimer(T3);

	while(time1[T3] <= 100)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = -15;
		motor[BR] = -15;
		motor[FL] = -15;
		motor[BL] = -15;
	}

	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	ClearTimer(T3);

	// raise wrist
	while(nMotorEncoder[wrist] <= -600 && time1[T3] <= 750)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;
		motor[wrist] = 40;
	}
	motor[wrist] = 0;
	ClearTimer(T3);


	// drive back
	while(time1[T3] <= 900)
	{
		if(checkCancel(joy1Btn(1), joy2Btn(1)))
			return;

		motor[FR] = -40;
		motor[BR] = -40;
		motor[FL] = -40;
		motor[BL] = -40;
	}

	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	return;
}

int takeAdump(int button, int stopbutton)
{
	static int Stop = 0;
	static int timelimit = 0;
	static int stage = 0;

	if(stopbutton)
		Stop = 1;
	else if(button)
	{
		Stop = 0;
		stage = 0;
		timelimit = 1500;
		ClearTimer(T4);
	}

	if(Stop)
	{
		motor[wrist] = 0;
		return 1;
	}

	if(time1[T4] >= timelimit)
	{
		motor[wrist] = 0;
		return 1;
	}

	if(stage == 0)
	{
		motor[wrist] = -40;
		if(nMotorEncoder[wrist] <= -1600)
		{
			motor[wrist] = 0;
			stage = 1;
		}
	}
	else if(stage == 1)
	{
		motor[wrist] = 40;
		if(nMotorEncoder[wrist] >= -800)
		{
			motor[wrist] = 0;
			Stop = 1;
			stage = 0;
			return 1;
		}
	}
	return 0;
}

void waywardSon(int button, int stopbutton)
{
	static int Stop = 0;
	const int timelimit = 3000;

	if(stopbutton)
		Stop = 1;
	else if(button)
	{
		Stop = 0;
		ClearTimer(T2);
	}

	if(Stop)
	{
		motor[arms] = 0;
		return;
	}

	if(time1[T2] >= timelimit)
	{
		Stop = 1;
		return;
	}

	if(nMotorEncoder[arms] <= -5000)
	{
		motor[arms] = -40;
	}
	else
	{
		motor[arms] = 0;
		Stop = 1;
	}

}

////////////////////////////////////////////////////////////////////////////// TASK MAIN!!! \(^0^)/

task main()
{

	clearDebugStream();
	int power = 0;
	ClearTimer(T1);
	ClearTimer(T4);
	int forward = 1;
	int joy1override = 0;
	nMotorEncoder[kicker1] = 0;
	nMotorEncoder[kicker2] = 0;
	writeDebugStreamLine("arm encoder %d" , nMotorEncoder[arms]);

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);

		if(time1[T1] >= 750)
		{
			writeDebugStreamLine("arm encoder %d" , nMotorEncoder[arms]);
			writeDebugStreamLine("wrist encoder %d" , nMotorEncoder[wrist]);
			writeDebugStreamLine("kicker encoder %d" , nMotorEncoder[kicker1]);
			ClearTimer(T1);
		}

		if(joy2Btn(10))
		{
			nMotorEncoder[arms] = 0;
			nMotorEncoder[wrist] = 0;
		}

		if(joy1Btn(9))
			joy1override = 1;
		else if(joy1Btn(10))
			joy1override = 0;

		kickTheBucket(joy1Btn(3), joy1Btn(1));
		takeAdump(joy2Btn(2), joy2Btn(1));
		waywardSon(joy2Btn(4), joy2Btn(1));

		if(joy2Btn(3))
			takeAbite();

		int driverCommandedArmPower = 0;
		if(abs(joystick.joy2_y1) > JOY_THRESH)
		{
			armMode = DRIVER;
			driverCommandedArmPower = 80;
			if(joystick.joy2_y1 > 0)
			{
				power *= -1;
			}
			driverCommandedArmPower = power;
		}

		switch(armMode){
		case DRIVER:
			motor[arms] = driverCommandedArmPower;
			break;
		case WAYWARD_SON:
			motor[arms] = waywardSon(DUMP_HEIGHT);
			break;
		case LIFTING:
			motor[arms] = waywardSon(HANG_HEIGHT);
			break;
		}

		if(takeAdump(joy2Btn(2), joy2Btn(1)))
		{
			if(abs(joystick.joy2_y2) > JOY_THRESH)
			{
				power = 30;
				if(joystick.joy2_y2 < 0)
				{
					power *= -1;
				}
				motor[wrist] = power;
			}
			else
				motor[wrist] = 0;
		}

		if(joy2Btn(7))
			motor[hookWinch] = 90;

		else if(joy2Btn(8))
			motor[hookWinch] = -90;

		else
			motor[hookWinch] = 0;

		if(joy1Btn(7))
			motor[tailWinch] = - 50;
		else if(joy1Btn(8))
			motor[tailWinch] = 90;

		else
			motor[tailWinch] = 0;

		if(joy1override)
		{
			if(joy1Btn(3))
			{
				motor[kicker1] = 100;
				motor[kicker2] = 100;
			}
			else if(joy1Btn(1))
			{
				motor[kicker1] = -100;
				motor[kicker2] = -100;
			}
			else
			{
				motor[kicker1] = 0;
				motor[kicker2] = 0;
			}
		}



		/////////////////////////////////////////////////

		float leftpower = 0;
		float rightpower = 0;
		int slow = 0;
		int xslow = 0;

		if(joy1Btn(2))
			forward = 0;
		else if(joy1Btn(4))
			forward = 1;

		int yaxis = joystick.joy1_y2;
		int xaxis = joystick.joy1_x1;

		leftpower = yaxis + xaxis;
		rightpower = yaxis - xaxis;

		//change "gears"
		if(joy1Btn(5))
			xslow = 1;
		else if(joy1Btn(6))
			slow = 1;
		else
		{
			slow = 0;
			xslow = 0;
		}

		if(xslow)
		{
			leftpower /= 3;
			rightpower /= 3;
		}

		else if(slow)
		{
			leftpower /= 2;
			rightpower /= 2;
		}

		//scale from joystick outputs to motors
		leftpower = (leftpower*100)/128;
		rightpower = (rightpower*100)/128;

		//if a side would get insignificant power just turn it off
		if(abs(leftpower) < 10)
			leftpower = 0;
		if(abs(rightpower) < 10)
			rightpower = 0;
		if(forward)
		{
			motor[FL] = leftpower;
			motor[BL] = leftpower;
			motor[FR] = rightpower;
			motor[BR] = rightpower;
		}
		else
		{
			motor[FR] = leftpower;
			motor[BR] = leftpower;
			motor[FL] = rightpower;
			motor[BL] = rightpower;
		}
	}
}
