#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

#define TURN_JOY_THRESH 50

#define INT_POWER 50

#define CHECK_TIME  40

#define STALL_VALUE  12

void kickTheBucket(int button, int stopbutton)
{
	static int Stop = 0;
	static int timelimit = 0;
	static int stage = 0;

	if(stopbutton)
		Stop = 1;
	else if(button)
	{
		Stop = 0;
		stage = 0;
		timelimit = time1[T4] + 1500;
	}

	if(Stop)
		return;

	if(time1[T4] >= timelimit)
	{
		motor[kicker1] = 0;
		motor[kicker2] = 0;
		return;
	}
	if(stage == 0)
	{
		motor[kicker1] = 100;
		motor[kicker2] = 100;
		if(nMotorEncoder[kicker1] >= 750)
		{
			motor[kicker1] = 0;
			motor[kicker2] = 0;
			stage = 1;
		}
	}
	else if(stage == 1)
	{
		motor[kicker1] = -50;
		motor[kicker2] = -50;
		if(nMotorEncoder[kicker1] <= 0)
		{
			motor[kicker1] = 0;
			motor[kicker2] = 0;
			stage = 2;
		}
	}
}


task main()
{

	clearDebugStream();
	int power = INT_POWER;
	nMotorEncoder[arms] = 0;
	nMotorEncoder[wrist] = 0;
	ClearTimer(T1);
	ClearTimer(T4);
	int forward = 1;
	int extra = 0;

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);

		kickTheBucket(joy1Btn(3), joy1Btn(1));


		if(abs(joystick.joy2_y1) > JOY_THRESH) //second joystick controls arm
		{
			power = 80;
			if(joystick.joy2_y1 > 0)
			{
				power *= -1;
			}
			motor[arms] = power;
		}
		else
			motor[arms] = 0;

			if(joy1Btn(5))
				extra = 50;

		if(joy2Btn(4))
		{
			//motor[wrist1] = 100;
			//motor[wrist2] = 100;//Move wrist down
			motor[wrist] = 25;
		}

		else if(joy2Btn(2))
		{
			//motor[wrist1] = -100;  //Move wrist up
			//motor[wrist2] = -100;
			motor[wrist] = -25;
		}

		else
		{
			//motor[wrist1] = 0;
			//motor[wrist2] = 0;
			motor[wrist] = 0;
		}

		if(joy2Btn(7))
			motor[hookWinch] = 90;

		else if(joy2Btn(8))
			motor[hookWinch] = -90;

		else
			motor[hookWinch] = 0;

		if(joy1Btn(7))
			motor[tailWinch] = - 50;
		else if(joy1Btn(8))
			motor[tailWinch] = 90;

		else
			motor[tailWinch] = 0;

		//if(joy1Btn(3))
		//{
		//	motor[kicker1] = 100;
		//	motor[kicker2] = 100;
		//}
		//else if(joy1Btn(1))
		//{
		//	motor[kicker1] = -100;
		//	motor[kicker2] = -100;
		//}
		//else
		//{
		//	motor[kicker1] = 0;
		//	motor[kicker2] = 0;
		//}
		//writeDebugStreamLine("nxt encoder: %d" , nMotorEncoder[kicker1]);



		/////////////////////////////////////////////////

		float leftpower = 0;
		float rightpower = 0;
		int slow = 0;
		int xslow = 0;

		if(joy1Btn(2))
			forward = 0;
		else if(joy1Btn(4))
			forward = 1;

		float yaxis = joystick.joy1_y1;
		float xaxis = joystick.joy1_x2;
		float angle = radiansToDegrees(atan(abs(yaxis)/abs(xaxis)));

		//if only one joystick is reading just look at it
		if(abs(xaxis) <= JOY_THRESH)
		{
			leftpower = yaxis;
			rightpower = -yaxis;
		}

		else if(abs(yaxis) <= JOY_THRESH)
		{
			leftpower = xaxis;
			rightpower = xaxis;
		}

		//otherwise do the math for a curve turn
		else if(xaxis > 0 && yaxis > 0)
		{
			leftpower = sqrt(pow(xaxis,2) + pow(yaxis,2));
			rightpower = -1 * (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
		}
		else if(xaxis < 0 && yaxis > 0)
		{
			leftpower = (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
			rightpower = -1 * sqrt(pow(xaxis,2) + pow(yaxis,2));
		}
		else if(xaxis < 0 && yaxis < 0)
		{
			leftpower = -1 * (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
			rightpower = sqrt(pow(xaxis,2) + pow(yaxis,2));
		}
		else if(xaxis > 0 && yaxis < 0)
		{
			leftpower = -1 * sqrt(pow(xaxis,2) + pow(yaxis,2));
			rightpower = (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
		}

		else
		{
			leftpower = 0;
			rightpower = 0;
		}

		//change "gears"
		if(joy1Btn(5))
			xslow = 1;
		else if(joy1Btn(6))
			slow = 1;
		else
		{
			slow = 0;
			xslow = 0;
		}

		if(xslow)
		{
			leftpower /= 3;
			rightpower /= 3;
		}

		else if(slow)
		{
			leftpower /= 2;
			rightpower /= 2;
		}

		//scale from joystick outputs to motors
		leftpower = (leftpower*100)/128;
		rightpower = (rightpower*100)/128;

		//if a side would get insignificant power just turn it off
		if(abs(leftpower) < 10)
			leftpower = 0;
		if(abs(rightpower) < 10)
			rightpower = 0;
		if(forward)
		{
			motor[FL] = -leftpower;
			motor[BL] = -leftpower;
			motor[FR] = -rightpower;
			motor[BR] = -rightpower;
		}
		else
		{
			motor[FR] = -leftpower;
			motor[BR] = -leftpower;
			motor[FL] = -rightpower;
			motor[BL] = -rightpower;
		}


	}
}
