#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          wrist1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          wrist2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

task main()
{
	//int power = 0;
	//int slow = 0;
	nMotorEncoder[wrist1] = 0;
	nMotorEncoder[arms] = 0;

	clearDebugStream();

	while(1)
	{
		wait10Msec(100);
		//getJoystickSettings(joystick);

		writeDebugStreamLine("wrist %d" , nMotorEncoder[wrist1]);
		writeDebugStreamLine("arms %d" , nMotorEncoder[arms]);

		//if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //turn
		//		{
		//			power = abs(joystick.joy1_x2) - JOY_THRESH;

		//			if(slow)
		//				power /= 3;
		//			if( joystick.joy1_x2 > 0 )
		//				power *= -1;
		//			motor[FL] = power;
		//			motor[BL] = power;
		//			motor[FR] = power;
		//			motor[BR] = power;

		//		}
		//		else if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
		//		{
		//			power = abs(joystick.joy1_y1) - JOY_THRESH;

		//			if(slow)
		//				power /= 3;
		//			if ( joystick.joy1_y1 > 0 )
		//				power *= -1;
		//			motor[FL] = power;
		//			motor[BL] = power;
		//			motor[FR] =  -1 * power;
		//			motor[BR] =  -1 * power;

		//		}
		//		else
		//		{
		//			motor[FL] = 0;
		//			motor[BL] = 0;
		//			motor[FR] = 0;
		//			motor[BR] = 0;
		//		}

	}



}
