#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     foot,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     wench,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

task main()
{

	while(1)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(1))
			motor[foot] = 90;
		else if(joy1Btn(3))
			motor[foot] = -90;
		else
			motor[foot] = 0;

		if(joy1Btn(2))
			motor[wench] = 90;

		else if(joy1Btn(4))
			motor[wench] = -90;
		else
			motor[wench] = 0;



	}
}
