#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          wrist1,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          wrist2,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     stick,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

#define INT_POWER 50

#define CHECK_TIME  40

#define STALL_VALUE  12

void carryArm( int button, int up, int down)
{
	static int HIGH_ARM_VALUE = 1000;
	static int LOW_ARM_VALUE = 990;
	static int timesStill = 0;
	static int lastPositon = 0;
	static int armPower = 0;
	static int lastButton = 0;
	int curPositon = nMotorEncoder[arms];

	if(curPositon < 0)
		nMotorEncoder[arms] = 0;

	if(up)
	{
		HIGH_ARM_VALUE += 5;
		LOW_ARM_VALUE += 5;
	}

	if(down)
	{
		HIGH_ARM_VALUE -= 5;
		LOW_ARM_VALUE -= 5;

	}

	if(!button) // the button wasn't pressed
	{
		if(lastButton) // and the last time it was: reset everything
		{
			motor[arms] = 0;
			timesStill = 0;
			lastPositon = curPositon;
			armPower = 0;
			lastButton = 0;
		}
		return;
	}

	//	writeDebugStreamLine("curPositon %d" , curPositon);

	if(!lastButton)
	{
		timesStill = 0;
		lastPositon = curPositon;

		if(curPositon >= LOW_ARM_VALUE)
		{
			timesStill = 0;
			lastPositon = curPositon;
			armPower = 0;
			motor[arms] = armPower;
			return;
		}
	}
	lastButton = button;


	if( time1[T1] > CHECK_TIME ) // if its time to check
	{
		ClearTimer(T1);
		if(curPositon >= HIGH_ARM_VALUE)
		{
			timesStill = 0;
			lastPositon = curPositon;
			armPower = 0;
			motor[arms] = armPower;
			return;
		}

		if(curPositon <= LOW_ARM_VALUE && armPower == 0 && timesStill < STALL_VALUE)
		{
			timesStill = 0;
			lastPositon = curPositon;
			armPower = 40;
			writeDebugStream("set power %d timesStill %d \n", armPower, timesStill);
			motor[arms] = armPower;
			return;
		}

		int change = lastPositon - curPositon;
		writeDebugStream("set power %d timesStill %d change %d encoder %d \n", armPower , timesStill , change, curPositon);


		if( timesStill > STALL_VALUE ) // if it hasnt moved in the past few iterations
		{
			armPower = 0;
			motor[arms] = armPower;
			timesStill ++;
			return;
		}

		if(change < 1)
		{
			timesStill ++;
			armPower = 100;
			writeDebugStream("set power %d timesStill %d change %d \n", armPower , timesStill, change);
			motor[arms] = armPower;
			lastPositon = curPositon;
			return;
		}

		lastPositon = curPositon;
		timesStill = 0;

		//if(nMotorEncoder[arms] >= CARRY_ENCODER_VALUE) // if it has reached the point it should be at
		//{
		//	motor[arms] = 0;
		//	timesStill = 0;
		//	return;
		//}

		//if(nMotorEncoder[arms] < CARRY_ENCODER_VALUE) // if it hasnt gotten there yet
		//{
		//	if((nMotorEncoder[arms] - lastPositon) > 0) // if it moved last time: just keep going
		//	{
		//		timesStill = 0;
		//		return;
		//	}
		//	else // if it hasnt moved but power was applied
		//	{
		//		armPower += 5; // add power
		//		timesStill += 1; // and increment the variable
		//	}
		//	motor[arms] = armPower;
		//}


	}

	return;

}

void carryWrist( int button)
{
	static int wristTarget = 0;
	static int lastButton = 0;
	static int startPosition = 0;

	if(!button)
	{
		if(lastButton)
		{
			motor[wrist1] = 0;
			motor[wrist2] = 0;
			lastButton = 0;
		}
		return;
	}

	if(!lastButton)
	{
		nMotorEncoder[wrist1] = 0;
		startPosition = nMotorEncoder[arms];
	}
	lastButton = button;
	wristTarget = (nMotorEncoder[arms] - startPosition)/9;

	if(button)
	{

		if(joy2Btn(2) || joy2Btn(4))
			return;

		if(nMotorEncoder[wrist1] > (wristTarget + 2))
		{
			motor[wrist1] = -50;
			motor[wrist2] = -50;
			return;
		}

		if(nMotorEncoder[wrist1] < (wristTarget - 2))
		{
			motor[wrist1] = 50;
			motor[wrist2] = 50;
			return;
		}

		else
		{
			motor[wrist1] = 0;
			motor[wrist2] = 0;
			return;
		}
	}
}



task main()
{

	clearDebugStream();
	int power = INT_POWER;
	int slow = 0;
	nMotorEncoder[arms] = 0;
	nMotorEncoder[wrist1] = 0;
	int brake = 0;

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);

		carryArm( joy2Btn(5), joy2Btn(10), joy2Btn(9));
		carryWrist( joy2Btn(5));


		//if(joy1Btn(2))
		//	motor[arms] = -50;

		//else if(joy1Btn(4))
		//	motor[arms] = 60;

		if(joy1Btn(4))
			brake = 1;
		else if (joy1Btn(2))
			brake = 0;

		if(!joy2Btn(5))
		{

			if(abs(joystick.joy2_y1) > JOY_THRESH) //Control goes to the second joystick
			{
				power = 80;
				if(joystick.joy2_y1 < 0)
				{
					power *= -1;
					power /= 2; //Moving the arm down is easy and low-power
				}
				motor[arms] = power;
			}
			else
				motor[arms] = 0;

		}


		if(joy2Btn(4))
		{
			motor[wrist1] = -100;
			motor[wrist2] = -100;//Move wrist up
		}

		else if(joy2Btn(2))
		{
			motor[wrist1] = 75;  //Move wrist down
			motor[wrist2] = 75;
		}

		else
		{
			if(!joy2Btn(5))
			{
				motor[wrist1] = 0;
				motor[wrist2] = 0;
			}
		}

		if(joy1Btn(5))
			slow = 1;
		else
			slow = 0;

		if(joy2Btn(7) || joy1Btn(7))
			motor[hookWinch] = 60;

		else if(joy2Btn(8) || joy1Btn(8))
			motor[hookWinch] = -60;

		else
			motor[hookWinch] = 0;

		if(abs(joystick.joy2_x2) > JOY_THRESH)
		{
			if(joystick.joy2_x2 < 0)
				motor[tailWinch] = - 50;
			else
				motor[tailWinch] = 50;
		}

		else
			motor[tailWinch] = 0;

		if(joy1Btn(1))
			motor[stick] = -50;

		else if(joy1Btn(3))
			motor[stick] = 50;

		else
			motor[stick] = 0;

		if(!brake)
		{


			if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //turn
			{
				power = abs(joystick.joy1_x2) - JOY_THRESH;

				if(slow)
					power /= 3;
				if( joystick.joy1_x2 > 0 )
					power *= -1;
				motor[FL] = power;
				motor[BL] = power;
				motor[FR] = power;
				motor[BR] = power;

			}
			else if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
			{
				power = abs(joystick.joy1_y1) - JOY_THRESH;

				if(slow)
					power /= 3;
				if ( joystick.joy1_y1 > 0 )
					power *= -1;
				motor[FL] = power;
				motor[BL] = power;
				motor[FR] =  -1 * power;
				motor[BR] =  -1 * power;

			}
			else
			{
				motor[FL] = 0;
				motor[BL] = 0;
				motor[FR] = 0;
				motor[BR] = 0;
			}
		}
		else
		{
			motor[FL] = 0;
			motor[BL] = 0;
			motor[FR] = 0;
			motor[BR] = 0;
		}

	}


}
