#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          wrist1,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          wrist2,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     stick,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


#define JOY_THRESH 12

#define TURN_JOY_THRESH 50

#define INT_POWER 50

#define CHECK_TIME  40

#define STALL_VALUE  12

task main()
{

	clearDebugStream();
	int power = INT_POWER;
	int slow = 0;
	int turnAdjustment = 0;
	nMotorEncoder[arms] = 0;
	nMotorEncoder[wrist1] = 0;
	int brake = 0;

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);
		//writeDebugStreamLine(" arm encoder %d" , nMotorEncoder[arms]);

		//if(joy1Btn(2))
		//	motor[arms] = -50;

		//else if(joy1Btn(4))
		//	motor[arms] = 60;

		if(joy1Btn(4))
			brake = 1;
		else if (joy1Btn(2))
			brake = 0;


		if(abs(joystick.joy2_y1) > JOY_THRESH) //Control goes to the second joystick
		{
			power = 80;
			if(joystick.joy2_y1 > 0)
			{
				power *= -1;
				power /= 2; //Moving the arm down is easy and low-power
			}
			motor[arms] = power;
		}
		else
			motor[arms] = 0;




		if(joy2Btn(4))
		{
			motor[wrist1] = 100;
			motor[wrist2] = 100;//Move wrist down
		}

		else if(joy2Btn(2))
		{
			motor[wrist1] = -100;  //Move wrist up
			motor[wrist2] = -100;
		}

		else
		{
			motor[wrist1] = 0;
			motor[wrist2] = 0;
		}

		if(joy1Btn(5))
			slow = 1;
		else
			slow = 0;

		if(joy2Btn(7) || joy1Btn(7))
			motor[hookWinch] = 60;

		else if(joy2Btn(8) || joy1Btn(8))
			motor[hookWinch] = -60;

		else
			motor[hookWinch] = 0;

		if(abs(joystick.joy2_x2) > JOY_THRESH)
		{
			if(joystick.joy2_x2 < 0)
				motor[tailWinch] = - 50;
			else
				motor[tailWinch] = 50;
		}

		else
			motor[tailWinch] = 0;

		if(joy1Btn(1))
			motor[stick] = -50;

		else if(joy1Btn(3))
			motor[stick] = 50;

		else
			motor[stick] = 0;

		if(!brake)
		{

			if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
			{
				power = abs(joystick.joy1_y1) - JOY_THRESH;

				if(slow)
					power /= 3;

				if ( joystick.joy1_y1 > 0 )
					power *= -1;

				if(abs(joystick.joy1_x2) <= JOY_THRESH)
				{
					motor[FL] = power;
					motor[BL] = power;
					motor[FR] =  -1 * power;
					motor[BR] =  -1 * power;
					continue;
				}
				else if(abs(joystick.joy1_x2) > JOY_THRESH && abs(joystick.joy1_x2) >= TURN_JOY_THRESH)
					turnAdjustment = 50;

				else
					turnAdjustment = abs(joystick.joy1_x2);

				if(slow)
					turnAdjustment /= 2;

				if(joystick.joy1_x2 < 0)
				{
					motor[FL] = power - turnAdjustment;
					motor[BL] = power - turnAdjustment;
					motor[FR] =  -1 * power;
					motor[BR] =  -1 * power;
				}
				else
				{
					motor[FL] = power;
					motor[BL] = power;
					motor[FR] =  -1 * power - turnAdjustment;
					motor[BR] =  -1 * power - turnAdjustment;
				}
			}

			else if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //spin turn
			{
				power = abs(joystick.joy1_x2) - JOY_THRESH;

				if(slow)
					power /= 3;
				if( joystick.joy1_x2 > 0 )
					power *= -1;
				motor[FL] = power;
				motor[BL] = power;
				motor[FR] = power;
				motor[BR] = power;

			}

			else
			{
				motor[FL] = 0;
				motor[BL] = 0;
				motor[FR] = 0;
				motor[BR] = 0;
			}
		}
		else
		{
			motor[FL] = 0;
			motor[BL] = 0;
			motor[FR] = 0;
			motor[BR] = 0;
		}
	}
}
