#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          wrist1,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          wrist2,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     stick,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 25

#define TURN_JOY_THRESH 50

#define INT_POWER 50

#define CHECK_TIME  40

#define STALL_VALUE  12

//void setPhasersToDoubletap(int button, int cancel)
//{
//	static int stage = 0;
//	static int doubleTap = 0;
//	static int lastButton = 0;

//	if(cancel)
//	{
//		ClearTimer(T3);
//			motor[stick] = 0;
//			lastButton = 0;
//			doubleTap = 0;
//			stage = 0;
//	}

//	if(!button)
//	{
//		if(lastButton)
//		{
//			ClearTimer(T3);
//			motor[stick] = 0;
//			lastButton = 0;
//			doubleTap = 0;
//			stage = 0;
//		}

//		return;
//	}

//	if(doubleTap && time1[T3] > 500)
//	{
//		doubleTap = 0;
//		motor[stick] = 0;
//		return;
//	}

//	if(!lastButton)
//	{
//		if(time1(T3) < 250)
//		{
//			ClearTimer(T3);
//			motor[stick] = -50;
//			doubleTap = 1;
//			return;
//		}
//		ClearTimer(T2);
//		motor[stick] = -50;
//		lastButton = button;
//		return;
//	}

//	if(time1[T2] > 500)
//	{
//		motor[stick] = 0;
//		stage = 1;
//	}

//	if(stage)
//	{
//		ClearTimer(T2);
//		motor[stick] = 50;
//		if(time1[T2] > 500)
//		{
//			motor[stick] = 0;
//			stage = 0;
//		}
//	}

//}

task main()
{

	clearDebugStream();
	int power = INT_POWER;
	int slow = 0;
	nMotorEncoder[arms] = 0;
	nMotorEncoder[wrist1] = 0;
	int brake = 0;
	ClearTimer(T1);

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);
		//writeDebugStreamLine(" arm encoder %d" , nMotorEncoder[arms]);

		//if(joy1Btn(2))
		//	motor[arms] = -50;

		//else if(joy1Btn(4))
		//	motor[arms] = 60;

		//setPhasersToDoubletap(joy1Btn(3), joy1Btn(1));

		//if(joy1Btn(4))
		//	brake = 1;
		//else if (joy1Btn(2))
		//	brake = 0;


		if(abs(joystick.joy2_y1) > JOY_THRESH) //Control goes to the second joystick
		{
			power = 80;
			if(joystick.joy2_y1 > 0)
			{
				power *= -1;
			}
			motor[arms] = power;
		}
		else
			motor[arms] = 0;




		if(joy2Btn(4))
		{
			motor[wrist1] = 100;
			motor[wrist2] = 100;//Move wrist down
		}

		else if(joy2Btn(2))
		{
			motor[wrist1] = -100;  //Move wrist up
			motor[wrist2] = -100;
		}

		else
		{
			motor[wrist1] = 0;
			motor[wrist2] = 0;
		}

		if(joy1Btn(5))
			slow = 1;
		else
			slow = 0;

		if(joy2Btn(7))
			motor[hookWinch] = 90;

		else if(joy2Btn(8))
			motor[hookWinch] = -90;

		else
			motor[hookWinch] = 0;

		if(joy1Btn(7))
			motor[tailWinch] = - 50;
		else if(joy1Btn(8))
			motor[tailWinch] = 90;

		else
			motor[tailWinch] = 0;

		if(joy1Btn(3))
			motor[stick] = -50;
		else if(joy1Btn(1))
			motor[stick] = 50;
		else
			motor[stick] = 0;

		/////////////////////////////////////////////////

		float leftpower = 0;
		float rightpower = 0;
		int slow = 0;
		int fast = 0;

		if(!brake)
		{

			float yaxis = joystick.joy1_y2;
			float xaxis = joystick.joy1_x1;
			float angle = radiansToDegrees(atan(abs(yaxis)/abs(xaxis)));

			//if(joy1_TopHat == 0)
			//{
			//	leftpower = 50;
			//	rightpower = -50;
			//}

			//else if(joy1_TopHat == 2)
			//{
			//	leftpower = 50;
			//	rightpower = 50;
			//}

			//else if(joy1_TopHat == 4)
			//{
			//	leftpower = -50;
			//	rightpower = 50;
			//}

			//else if(joy1_TopHat == 6)
			//{
			//	leftpower = 50;
			//	rightpower = 50;
			//}

			if(abs(xaxis) <= JOY_THRESH)
			{
				leftpower = yaxis;
				rightpower = -yaxis;

			}

			else if(abs(yaxis) <= JOY_THRESH)
			{
				leftpower = xaxis;
				rightpower = xaxis;
			}

			else if(xaxis > 0 && yaxis > 0)
			{
				leftpower = sqrt(pow(xaxis,2) + pow(yaxis,2));
				rightpower = -1 * (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
			}
			else if(xaxis < 0 && yaxis > 0)
			{
				leftpower = (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
				rightpower = -1 * sqrt(pow(xaxis,2) + pow(yaxis,2));
			}
			else if(xaxis < 0 && yaxis < 0)
			{
				leftpower = -1 * (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
				rightpower = sqrt(pow(xaxis,2) + pow(yaxis,2));
			}
			else if(xaxis > 0 && yaxis < 0)
			{
				leftpower = -1 * sqrt(pow(xaxis,2) + pow(yaxis,2));
				rightpower = (sqrt(pow(xaxis,2) + pow(yaxis,2))/100)*((10/9)*angle);
			}

			else
			{
				leftpower = 0;
				rightpower = 0;
			}

			if(joy1Btn(5))
				slow = 1;
			else if(joy1Btn(6))
				fast = 1;
			else
			{
				slow = 0;
				fast = 0;
			}

			if(slow)
			{
				leftpower /= 3;
				rightpower /= 3;
			}

			else if(!fast || (fast && slow))
			{
				leftpower /= 2;
				rightpower /= 2;
			}

			leftpower = (leftpower*100)/128;
			rightpower = (rightpower*100)/128;

			if(abs(leftpower) < 10)
				leftpower = 0;
			if(abs(rightpower) < 10)
				rightpower = 0;

			//if(time10[T1] >= 50)
			//{
			//	ClearTimer(T1);
			//	writeDebugStreamLine("leftpower %f" , leftpower);
			//	writeDebugStreamLine("rightpower %f" , rightpower);
			//}

			motor[FL] = -leftpower;
			motor[BL] = -leftpower;
			motor[FR] = -rightpower;
			motor[BR] = -rightpower;

		}
		else
		{
			motor[FL] = 0;
			motor[BL] = 0;
			motor[FR] = 0;
			motor[BR] = 0;
		}
	}
}
