#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          sweeper,       tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FR,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

task main()
{
	int power;
	int boost = 0;
	int precision = 0;
	//waitForStart();
	while(1)
	{
		getJoystickSettings(joystick);
		if ( joy1Btn(6))
			boost = 50;
		else
			boost = 0;
		if ( joy1Btn(5))
			precision = 20;
		else
			precision = 0;

		if(joy1Btn(2))
		{
			ClearTimer(T1);
			while(time1[T1] < 700)
			{
				motor[sweeper] = -25;
			}
		}
		if(joy1Btn(3))
		{
			ClearTimer(T1);
			while(time1[T1] < 700)
			{
				motor[sweeper] = 25;
			}
		}
		else
			motor[sweeper] = 0;

		if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //turn
		{
			power = 25 + boost;
			if( joystick.joy1_x2 < 0 )
				power = -25 - boost;
			motor[FR] = power;
			motor[BR] = power;
			motor[FL] = power;
			motor[BL] = power;
		}
		else if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
		{
			power = -40 - boost + precision;
			if ( joystick.joy1_y1 < 0 )
				power = 40 + boost - precision;
			motor[FR] = power;
			motor[BR] = power;
			motor[FL] = -power;
			motor[BL]  = -power;
		}

		else
		{
			motor[FR] = 0;
			motor[BR] = 0;
			motor[FL] = 0;
			motor[BL] = 0;
		}

	}


}
