#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          grasp,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RM,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LM,            tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     LF,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     RB,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     LB,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     ARM,           tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

task main()
{

	waitForStart();

	int power = 0;

	while(1)
	{

		getJoystickSettings(joystick);
		ClearTimer(T1);

		if(joy1Btn(1))
		{
			while(nMotorEncoder[grasp] < 45 && time1[T1] < 50)
				motor[grasp] = 25;
			nMotorEncoder[grasp] = 0;
		}
		else if(joy1Btn(3))
		{
			while(nMotorEncoder[grasp] > -45 && time1[T1] < 50)
				motor[grasp] = -75;
			nMotorEncoder[grasp] = 0;
		}
		else
			motor[grasp] = 0;

		if(joy1Btn(4))
		{
			while(time1[T2] < 500 && joy1Btn(4))
			{
				getJoystickSettings(joystick);
				motor[ARM] = 50;
			}
			motor[ARM] = 0;
		}
		else if (joy1Btn(2))
		{
			while(time1[T2] < 500 && joy1Btn(2))
			{
				getJoystickSettings(joystick);
				motor[ARM] = -10;
			}
			motor[ARM] = 0;
		}
		else
		{
			ClearTimer(T2);
			motor[ARM] = 0;
		}
		if(abs(joystick.joy1_x2) > JOY_THRESH) //turn
		{
			power = joystick.joy1_x2/2;
			power = -power;
			motor[LM] = power;
			motor[RM] = power;
		}
		else if(abs(joystick.joy1_y1) > JOY_THRESH) //straight
		{
			power = joystick.joy1_y1;
			power = -power;
			motor[LF] = power;
			motor[LM] = power;
			motor[LB] = power;
			motor[RF] = -1 * power;
			motor[RM] = -1 * power;
			motor[RB] = -1 * power;
		}
		else
		{
			motor[LF] = 0;
			motor[LM] = 0;
			motor[LB] = 0;
			motor[RF] = 0;
			motor[RM] = 0;
			motor[RB] = 0;
		}
	}

}
