#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

void turnToIR(){
	int dirAC;
	dirAC = SensorValue[IRseeker];
	int turnPower = (dirAC - 5)*10;
	motor[left] = turnPower;
	motor[right] = turnPower;
}

task main()
{
	waitForStart();

	int power = 0;
	int servTarget = 0;

	while(1)
	{

		getJoystickSettings(joystick);

		if( joy1Btn(2) )
		{
			servTarget = servTarget - 5;
			wait1Msec(50);
		}
		if( joy1Btn(4) )
		{
			servTarget = servTarget + 5;
			wait1Msec(50);
		}

		if( joy1Btn(1) )
		{
			turnToIR();
		}
		if(abs(joystick.joy1_x2) > JOY_THRESH) //turn
		{
			power = joystick.joy1_x2/2;
			power = power * -1;
			motor[left] = power;
			motor[right] = power;
		}
		if(abs(joystick.joy1_y1) > JOY_THRESH) //straight
		{
			power = joystick.joy1_y1/2;
			power = power * -1;
			motor[left] = power;
			motor[right] = -1 * power;
		}
		else
		{
			motor[left] = 0;
			motor[right] = 0;
		}
		servo[servo1] = servTarget;

	}
}
