#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 12

int gyroOffset = 594;			// set default value

float gyroVal = 0.0;

int gyroCal()
{
	int sum = 0;

	// Take 50 readings and average them out
	for (int i = 0; i < 50; i++)
	{
		sum += SensorValue(S2);
		wait1Msec(5);
	}

	// Store new offset
	gyroOffset = (sum / 50.0);

	ClearTimer(T2);			// reset gyro timer

	// Return new offset value
	return gyroOffset;
}

float updateGyro()
{
	if( time1[T2] > 4 )
	{
		int gVal = SensorValue(S2) - gyroOffset;
		if( motor[left] != 0 || motor[right] != 0 )
			gyroVal += (time1[T2] * gVal) / 1000.0;
		ClearTimer(T2);														// reset gyro timer
	}
	return gyroVal;
}

void resetGyro()
{
	gyroVal = 0;
	ClearTimer(T2);
}

int checkCancel()
{
	getJoystickSettings(joystick);
	if( joy1Btn(2) == 1 ||		joy1Btn(3) == 1 || joy1Btn(5) == 1 || joy1Btn(6) == 1)
	return 1;
	else
		return 0;
}

int turnG( int deg, int rightTurn, int power )
{
	int cancel = 0;
	resetGyro();
	if( rightTurn )
		power = -1 * power;

	while( abs(gyroVal) < deg )
	{
		motor[right] = power;
		motor[left] = power;
		updateGyro();
		if( checkCancel() == 1 )
		{
			cancel++;
			break;
		}
	}

	motor[right] = 0;
	motor[left] = 0;
	return cancel;
}


task main()
{
	gyroCal();
	//waitForStart();

	int power = 0;
	int servTarget = 0;

	while(1)
	{
		updateGyro();

		getJoystickSettings(joystick);

		if( joy1Btn(1) )
			turnG(90, 1, 25);

		if( joy1Btn(2) )
		{
			servTarget = servTarget - 5;
			wait10Msec(5);
		}
		if( joy1Btn(4) )
		{
			servTarget = servTarget + 5;
			wait10Msec(5);
		}
		if(abs(joystick.joy1_x2) > JOY_THRESH) //turn
		{
			power = joystick.joy1_x2/2;
			power = power * -1;
			motor[left] = power;
			motor[right] = power;
		}
		else if(abs(joystick.joy1_y1) > JOY_THRESH) //straight
		{
			power = joystick.joy1_y1/2;
			power = power * -1;
			motor[left] = power;
			motor[right] = -1 * power;
		}
		else
		{
			motor[left] = 0;
			motor[right] = 0;
		}
		servo[servo1] = servTarget;

	}
}
