#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 8
#define ACCEL_LIMIT 2

task main()
{
	float lastPower = 0;
	while(true)
	{
		getJoystickSettings(joystick);
		float leftPower = constrainToThresh(joystick.joy1_y1); //read joystick values



		motor[left] = leftPower;

		//motor[right] = constrainToThresh(joystick.joy1_y2);

		lastPower = leftPower;
	}


}

int constrainToThresh(int input){
	if(abs(input) < JOY_THRESH)
		return 0;

	return input;
}
