#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 3

task main()
{
	int power = 0;

	//waitForStart();
	while(1)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(2))
		{
			motor[left] = 0;
			motor[right] = 0;
			nMotorEncoder[arm] = 0;
			while(nMotorEncoder[arm] > - 360)
				motor[arm] = -100;

			while(nMotorEncoder[arm] < 0)
				motor[arm] = 30;
			motor[arm] =0;
		}

		else if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //turn
		{
			power = (abs(joystick.joy1_x2)-JOY_THRESH)/2;
			if( joystick.joy1_x2 > 0 )
				power *= -1;
			motor[left] = power;
			motor[right] = power;

		}
		else if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
		{
			power = (abs(joystick.joy1_y1) - JOY_THRESH)/2;
			//power = pow(power/100.0, 6)*100;
			if ( joystick.joy1_y1 < 0 )
				power *= -1;
			motor[left] = -power;
			motor[right] = power;

		}

		else
		{
			motor[left] = 0;
			motor[right] = 0;

		}


	}



}
