#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          wrist1,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          wrist2,        tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arms,          tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 10

#define INT_POWER 50

task main()
{

	int power = INT_POWER;
	int slow = 0;

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(2))
			motor[arms] = -50;

		else if(joy1Btn(4))
			motor[arms] = 60;

		else if(abs(joystick.joy2_y1) > JOY_THRESH){ //Control goes to the second joystick
			power = abs(joystick.joy2_y1) - JOY_THRESH;
			if(joystick.joy2_y1 < 0)
			{
				power *= -1;
				power /= 4; //Moving the arm down is easy and low-power
			}
			motor[arms] = power;
		}
		else
			motor[arms] = 0;

		if(joy1Btn(3) || joy2Btn(4))
		{
			motor[wrist1] = -100;
			motor[wrist2] = -100;//Move wrist up
		}

		else if(joy1Btn(1) || joy2Btn(2))
		{
			motor[wrist1] = 50;  //Move wrist down
			motor[wrist2] = 50;
		}

		else
		{
			motor[wrist1] = 0;
			motor[wrist2] = 0;
		}

		if(joy1Btn(5))
			slow = 1;
		else
			slow = 0;

		if(joy2Btn(7) || joy1Btn(7))
			motor[winch] = 60;

		else if(joy2Btn(8) || joy1Btn(8))
			motor[winch] = -60;

		else
			motor[winch] = 0;


		if( abs( joystick.joy1_x2 ) > JOY_THRESH ) //turn
		{
			power = abs(joystick.joy1_x2) - JOY_THRESH;
			if(slow)
				power /= 3;
			if( joystick.joy1_x2 < 0 )
				power *= -1;
			motor[left] = power;
			motor[right] = power;

		}
		else if( abs( joystick.joy1_y1 ) > JOY_THRESH ) //straight
		{
			power = abs(joystick.joy1_y1) - JOY_THRESH;
			if(slow)
				power /= 3;
			if ( joystick.joy1_y1 < 0 )
				power *= -1;
			motor[left] = power;
			motor[right] =  -1 * power;

		}

		else
		{
			motor[left] = 0;
			motor[right] = 0;
		}

	}


}
