#pragma config(Motor,  motorA,          a,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[a] = 0;
	while(1)
	{
		while(nMotorEncoder[a] < 180)
			motor[a]= 100;
		nMotorEncoder[a] = 0;
		while(nMotorEncoder[a]> -180)
			motor[a] = -100;
nMotorEncoder[a] =0;

	}

}
