#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          kicker1,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          kicker2,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     tailWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     hookWinch,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arms,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     wrist,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     FL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BL,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     FR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     BR,            tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOY_THRESH 10

#define TURN_JOY_THRESH 50

#define INT_POWER 50

#define CHECK_TIME  40

#define STALL_VALUE  12

task main()
{

	clearDebugStream();
	int power = INT_POWER;
	nMotorEncoder[arms] = 0;
	nMotorEncoder[wrist] = 0;
	ClearTimer(T1);
	int forward = 1;

	//waitForStart();


	while(1)
	{
		getJoystickSettings(joystick);


		if(abs(joystick.joy2_y1) > JOY_THRESH) //second joystick controls arm
		{
			power = 80;
			if(joystick.joy2_y1 > 0)
			{
				power *= -1;
			}
			motor[arms] = power;
		}
		else
			motor[arms] = 0;


		if(joy2Btn(4))
		{
			motor[wrist] = 50;
			//Move wrist down
		}

		else if(joy2Btn(2))
		{
			motor[wrist] = -50;  //Move wrist up

		}

		else
		{
			motor[wrist] = 0;
		}

		if(joy2Btn(7))
			motor[hookWinch] = 90;

		else if(joy2Btn(8))
			motor[hookWinch] = -90;

		else
			motor[hookWinch] = 0;

		if(joy1Btn(7))
			motor[tailWinch] = - 50;
		else if(joy1Btn(8))
			motor[tailWinch] = 90;

		else
			motor[tailWinch] = 0;

		if(joy1Btn(3))
		{
			motor[kicker1] = 100;
			motor[kicker2] = 100;
		}
		else if(joy1Btn(1))
		{
			motor[kicker1] = -100;
			motor[kicker2] = -100;
		}
		else
		{
			motor[kicker1] = 0;
			motor[kicker2] = 0;
		}

		/////////////////////////////////////////////////

		int leftpower = 0;
		int rightpower = 0;
		int slow = 0;
		int fast = 0;

		if(joy1Btn(2))
			forward = 0;
		else if(joy1Btn(4))
			forward = 1;

		if(abs(joystick.joy1_y1) > JOY_THRESH)
			leftpower = joystick.joy1_y1;
		else
			leftpower = 0;

		if(abs(joystick.joy1_y2) > JOY_THRESH)
			rightpower = joystick.joy1_y2;
		else
			rightpower = 0;

		//change "gears"
		if(joy1Btn(5))
			slow = 1;
		else if(joy1Btn(6))
			fast = 1;
		else
		{
			slow = 0;
			fast = 0;
		}

		if(slow)
		{
			leftpower /= 3;
			rightpower /= 3;
		}

		else if(!fast || (fast && slow))
		{
			leftpower /= 2;
			rightpower /= 2;
		}

		//scale from joystick outputs to motors
		leftpower = (leftpower*100)/128;
		rightpower = (rightpower*100)/128;

		//if a side would get insignificant power just turn it off
		if(abs(leftpower) < 10)
			leftpower = 0;
		if(abs(rightpower) < 10)
			rightpower = 0;
	if(forward)
	{
		motor[FL] = -leftpower;
		motor[BL] = -leftpower;
		motor[FR] = rightpower;
		motor[BR] = rightpower;
	}
	else
	{
		motor[FR] = -leftpower;
		motor[BR] = -leftpower;
		motor[FL] = rightpower;
		motor[BL] = rightpower;
	}


	}
}
