#pragma config(Motor,  motorA,          wiggly,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		motor[wiggly] = 100;

	}


}
