#pragma config(Sensor, S2,     seeker,         sensorI2CCustom)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          auxMotor,      tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          FrontL,        tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          FrontR,        tmotorNXT, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BALL-E overrides.c" //COMMENT OUT THIS LINE BEFORE RUNNING ON COMPETITION ROBOT


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "TrackerAutoLib.h"
#include "AutoLib.h"
#include "IRstuff.c"

#define DEBUG false

void initializeRobot()
{
	clearDebugStream();
	gyroCal();
	//servo[grabberServo]=???;
	//servo[dumperServo] =???;
	return;
}

int centerPos = -1;

void floorStart(){
	FieldPos p;
	memset(&p, 0, sizeof(p));

	p.x = 100;	p.y = 213.0; //Forward 80cm
	moveTo(p, 40);

	turnToHeading(degreesToRadians(-25), 30);

	centerPos = juliet(); //Take IR beacon reading

#ifdef BALLE
	centerPos = 2;
#endif

	writeDebugStreamLine("DETECTED CENTER STRUCTURE POSITION %d", centerPos);

	if (DEBUG) wait1Msec(4000);
	else wait1Msec(200);

	if(centerPos == 1)
	{
		p.x = 175; p.y = 265;
		turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);

		turnToHeading(degreesToRadians(-90), 40, Backward);

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);

		//turn(-45, 25);
		liftTallArm();

		p.x += 0; p.y -= 33;
		moveTo(p, 30, Backward, NO_STEERING);
		//move(-33, 30);
		dumpTallBalls();

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);


		p.x += 0; p.y += 15;
		moveTo(p, 30, Forward, NO_STEERING);
		//move(15, 30);
		lowerTallArm();


		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);


		p.x = 155; p.y = 250;
		turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);

		/*p.x = 155;*/ p.y = 170; //Hit kickstand
		turnAndMoveTo(p, 50);

		if (DEBUG){
			wait1Msec(2000);
			p.x = 22; p.y = 213; //Return to base
			turnAndMoveTo(p, 50);
			turnToHeading(degreesToRadians(0), 40);
		}
	}
	else if(centerPos == 2)///////////////////////////////////////////////////////////////////////////////////////////
	{
		//It just so happens that the position for delivery of the POSITION=2 ball is exactly the same as the IR sensing position.
		//p.x = 100; p.y = 213;
		//turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(1000);
		else wait1Msec(200);

		turnToHeading(degreesToRadians(-25), 40, Backward);

		if (DEBUG) wait1Msec(1000);
		else wait1Msec(200);

		liftTallArm();

		p.x += 30; p.y += -10;
		moveTo(p, 30, Backward, NO_STEERING);
		dumpTallBalls();

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);


		p.x -= 15; p.y += 5;
		moveTo(p, 30, Forward, NO_STEERING);
		lowerTallArm();


		if (DEBUG) wait1Msec(1000);
		else wait1Msec(200);


		p.x = 100; p.y = 190;
		turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);

		p.x = 180; p.y = 145; //Hit kickstand
		turnAndMoveTo(p, 50);

		if (DEBUG){
			wait1Msec(2000);
			p.x = 22; p.y = 213; //Return to base
			turnAndMoveTo(p, 50);
			turnToHeading(degreesToRadians(0), 40);
		}
	}
	else if(centerPos == 3)///////////////////////////////////////////////////////////////////////////////////////////
	{
		p.x = 100; p.y = 170;
		turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(1000);
		else wait1Msec(200);

		turnToHeading(degreesToRadians(0), 40, Backward);

		if (DEBUG) wait1Msec(1000);

		liftTallArm();

		p.x += 30; p.y += 0;
		moveTo(p, 30, Backward, NO_STEERING);
		dumpTallBalls();

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);


		p.x -= 15; p.y += 0;
		moveTo(p, 30, Forward, NO_STEERING);
		lowerTallArm();


		if (DEBUG) wait1Msec(1000);
		else wait1Msec(200);


		/*p.x = 110;*/ p.y = 155;
		turnAndMoveTo(p, 50);

		if (DEBUG) wait1Msec(2000);
		else wait1Msec(200);

		p.x = 195; /*p.y = 155;*/ //Hit kickstand
		turnAndMoveTo(p, 50);

		if (DEBUG){
			wait1Msec(2000);
			p.x = 22; p.y = 213; //Return to base
			turnAndMoveTo(p, 50);
			turnToHeading(degreesToRadians(0), 40);
		}
	}
	else writeDebugStreamLine("Detection of center structure failed in unexpected way.");
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	resetTracker();
	//Floor start tracking positions
	robot.x = 22.9; //9in, defined from robot
	robot.y = 213.0; //84in, measured
	robot.theta = 0.0;
	StartTask(trackRobot);

	floorStart();
}
